# Patient model

patient:
  simulator: "patientpsi"
  model: "hosted_vllm/openai/gpt-oss-120b"
  temperature: 1.0 # patientpsi's extraction setting
  max_tokens: 2000
  max_attempts: 5
  conversation_type: "plain"
  api_base: "http://convai-srv-03.cs.illinois.edu:9000/v1"
  max_turns: 16
